version: '3.6'

services:
  app:
    build:
      context: ./app
      target: base
    image: covid-api:prod
    ports:
      - 8000:80
    depends_on: 
      - db      
    command: ["./wait-for-it.sh", "db:5432", "-t", "0", "--", "../start.sh"]
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./app/.env
    volumes:
      - ./database/data:/data
      - ./database/sql:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5