version: '3'

services:
  app:
    build:
      context: ./app
      target: base
    image: covid-api:test
    ports:
      - 8000:80
    depends_on: 
      - db      
    command: ["./wait-for-it.sh", "db:5432", "-t", "0", "--", "../start-reload.sh"]
    volumes:
      - ./app:/app
    restart: on-failure
  db:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./app/.env
    volumes:
      - ./database/data:/data
      - ./database/sql:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data