version: '3'

services:
  app:
    build:
      context: ./app
      target: base
    image: covid-api:dev
    ports:
      - 8000:80
    depends_on: 
      - db      
    command: /start-reload.sh
    volumes:
      - ./app:/app
  db:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./app/.env
    volumes:
      - ./database/data:/data
      - ./database/sql:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data